services:
  aoostar-display:
    image: ghcr.io/ndrau/aoostar-wtr-max-display:latest
    container_name: aoostar-display
    restart: unless-stopped
    ports:
      - "3910:3000"
    devices:
      - /dev/serial/by-id/usb-Synwit_USB_Virtual_COM-if00:/dev/ttyACM0
    environment:
      DEVICE: /dev/ttyACM0
      DATA_DIR: /data
      PORT: "3000"
      HOSTNAME: 0.0.0.0
      TZ: Europe/Berlin
      API_TOKEN: change-me-to-a-long-random-token
    volumes:
      - /mnt/AndysFastStorage/docker/aoostar-display:/data
